#index:
#    path: /
#    controller: App\Controller\DefaultController::index
   
search:
    path: /search
    controller: App\Controller\BeerController::searchByFood
    
detail:
    path: /detail
    controller: App\Controller\BeerController::searchById
    